#index:
#    path: /
#    controller: App\Controller\DefaultController::index

home:
    path: /
    controller: App\Controller\HomeController::home
register:
    path: /register
    controller: App\Controller\RegistrationController::register
